spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:mysql://81.69.43.78:3306/admin-boot?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    #    url: jdbc:p6spy:mysql://81.69.43.78:3306/cloud-demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: task,.123
#  # redis相关配置
#  redis:
#    host: 81.69.43.78
#    database: 6
#    port: 6379
#    password:
#    lettuce:
#      pool:
#        # 连接池最大连接数，负值表示没有限制
#        max-active: 100
#        # 连接池最大阻塞等待时间 -1 表示没有限制
#        max-wait: -1ms
#        # 连接池中最大空闲连接
#        max-idle: 10
#        # 连接池中最小空闲连接
#        min-idle: 0
#    # 连接超时时间（毫秒）
#    timeout: 1000

# xss相关配置 和 去除空格相关配置
security:
  xss:
    enabled: true
    skip-url:
      - /api/v1/hello
  space:
    enabled: true
    skip-url:
      - /api/v1/hello


# 日志配置文件位置
logging:
  config: classpath:log/logback-spring-dev.xml
